import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function Home() {
  return (
    <div>
      <h1>Hi</h1>
    </div>
  );
}

export default Home;
